import type {
  AccelerationGoal,
  EmployeeProfile,
  Opportunity,
} from '../../domain/types.js'

/** Protagonist — matches the demo world. */
export const MARIA_ID = 'emp-maria-oliveira'

export const employees: EmployeeProfile[] = [
  {
    id: 'emp-mariana-santos',
    name: 'Mariana Santos',
    initials: 'MS',
    role: 'Principal Cloud Solution Architect',
    location: 'São Paulo, Brazil',
    timeZone: 'GMT-3',
    languages: ['Portuguese', 'English', 'Spanish'],
    skills: ['AI', 'Azure AI', 'Cloud Architecture', 'Machine Learning'],
    certifications: ['Azure Solutions Architect Expert', 'Azure AI Engineer'],
    availability: 'This week',
    mentor: true,
    optedIn: true,
    community: 'HOLA',
  },
  {
    id: 'emp-diego-fernandez',
    name: 'Diego Fernández',
    initials: 'DF',
    role: 'Senior Cloud Solution Architect',
    location: 'Madrid, Spain',
    timeZone: 'GMT+1',
    languages: ['Spanish', 'English'],
    skills: ['AI', 'Azure OpenAI', 'Solution Design', 'Data Platform'],
    certifications: ['Azure Solutions Architect Expert'],
    availability: 'Today',
    mentor: true,
    optedIn: true,
    community: 'HOLA',
  },
  {
    id: 'emp-priya-nair',
    name: 'Priya Nair',
    initials: 'PN',
    role: 'Cloud Solution Architect',
    location: 'Bengaluru, India',
    timeZone: 'GMT+5:30',
    languages: ['English', 'Hindi'],
    skills: ['AI', 'Kubernetes', 'Platform Engineering'],
    certifications: ['Azure Administrator Associate'],
    availability: 'Next week',
    mentor: false,
    optedIn: true,
  },
  {
    id: 'emp-lucas-rocha',
    name: 'Lucas Rocha',
    initials: 'LR',
    role: 'AI Specialist',
    location: 'Lisbon, Portugal',
    timeZone: 'GMT+0',
    languages: ['Portuguese', 'English'],
    skills: ['Machine Learning', 'MLOps', 'Python'],
    certifications: ['Azure AI Engineer'],
    availability: 'This week',
    mentor: true,
    optedIn: true,
    community: 'HOLA',
  },
  {
    id: 'emp-hannah-berg',
    name: 'Hannah Berg',
    initials: 'HB',
    role: 'Power Platform Architect',
    location: 'Berlin, Germany',
    timeZone: 'GMT+1',
    languages: ['German', 'English'],
    skills: ['Power Platform', 'Automation', 'Dataverse'],
    certifications: ['Power Platform Solution Architect'],
    availability: 'Today',
    mentor: true,
    optedIn: true,
  },
  {
    id: 'emp-omar-said',
    name: 'Omar Said',
    initials: 'OS',
    role: 'Data & AI Consultant',
    location: 'Dubai, UAE',
    timeZone: 'GMT+4',
    languages: ['Arabic', 'English'],
    skills: ['AI', 'Data Engineering', 'Fabric'],
    certifications: ['Azure Data Engineer'],
    availability: 'Next week',
    mentor: false,
    // Deliberately not opted in — must never appear in results.
    optedIn: false,
  },
]

export const goals: Record<string, AccelerationGoal> = {
  [MARIA_ID]: {
    employeeId: MARIA_ID,
    employee: 'Maria Oliveira',
    employeeInitials: 'MO',
    location: 'Recife, Brazil',
    title: 'Become a Principal Cloud Solution Architect in AI',
    horizon: '12–18 months',
    skillSignals: [
      { skill: 'Azure AI', level: 3, note: 'Growing — 2 recent projects' },
      { skill: 'Cloud Architecture', level: 4, note: 'Strong core skill' },
      { skill: 'Executive influence', level: 2, note: 'Development area' },
    ],
  },
}

export const opportunities: Record<string, Opportunity[]> = {
  [MARIA_ID]: [
    {
      id: 'opp-mentor',
      kind: 'Mentor',
      title: 'Mentorship with a Principal CSA in AI',
      owner: 'Mariana Santos',
      ownerInitials: 'MS',
      detail:
        'Principal Cloud Solution Architect who made the exact move you are targeting.',
      reason:
        'Walked the IC-to-Principal path in AI, speaks Portuguese, and is open to mentoring.',
      timeframe: 'Intro this week',
      action: 'Request mentorship',
      confirmation: 'Mentorship intro drafted',
      optedIn: true,
    },
    {
      id: 'opp-peer',
      kind: 'Peer',
      title: 'Peer working on the same AI architecture patterns',
      owner: 'Diego Fernández',
      ownerInitials: 'DF',
      detail: 'Senior CSA shipping Azure OpenAI solutions right now.',
      reason: 'Solving the same problems you are, and available today.',
      timeframe: 'Available today',
      action: 'Connect as peers',
      confirmation: 'Peer intro drafted',
      optedIn: true,
    },
    {
      id: 'opp-sponsor',
      kind: 'Sponsor',
      title: 'Sponsor who can advocate for stretch work',
      owner: 'Hannah Berg',
      ownerInitials: 'HB',
      detail: 'Architect lead who staffs cross-region AI engagements.',
      reason: 'Can open doors to the visible, stretch projects Principals are known for.',
      timeframe: 'Intro this week',
      action: 'Request sponsorship',
      confirmation: 'Sponsor intro drafted',
      optedIn: true,
    },
    {
      id: 'opp-shadow',
      kind: 'Shadow',
      title: 'Shadow a live executive AI briefing',
      owner: 'Lucas Rocha',
      ownerInitials: 'LR',
      detail: 'AI Specialist running an executive-facing ML review next week.',
      reason: 'Builds the executive-influence signal flagged as your development area.',
      timeframe: 'Next week',
      action: 'Ask to shadow',
      confirmation: 'Shadow request drafted',
      optedIn: true,
    },
    {
      id: 'opp-cohort',
      kind: 'Cohort',
      title: 'AI Architect growth cohort',
      owner: 'Priya Nair',
      ownerInitials: 'PN',
      detail: 'Six-week peer cohort for architects moving into AI leadership.',
      reason: 'Structured practice with peers at the same career inflection point.',
      timeframe: 'Starts next week',
      action: 'Join cohort',
      confirmation: 'Cohort request drafted',
      optedIn: true,
    },
    {
      id: 'opp-community',
      kind: 'Community',
      title: 'HOLA community for Latino technologists',
      owner: 'HOLA community',
      ownerInitials: 'HL',
      detail: 'Employee community where your language and context are understood.',
      reason: 'Cultural context and Portuguese-speaking network already in place.',
      timeframe: 'Open now',
      action: 'Join community',
      confirmation: 'Community intro drafted',
      optedIn: true,
    },
  ],
}
