import type { AccelerationGoal, EmployeeProfile, Opportunity } from './domain'

export const employeeProfiles: EmployeeProfile[] = [
  {
    id: 'mariana-santos',
    name: 'Mariana Santos',
    initials: 'MS',
    role: 'Principal Power Platform Architect',
    location: 'Sao Paulo, Brazil',
    timeZone: 'BRT (UTC-3)',
    languages: ['Portuguese', 'English'],
    skills: ['Dataverse DLP', 'Power Platform governance', 'Copilot Studio'],
    certifications: ['Power Platform Solution Architect Expert'],
    availability: 'Today',
    mentor: true,
    optedIn: true,
    community: 'HOLA',
  },
  {
    id: 'tiago-costa',
    name: 'Tiago Costa',
    initials: 'TC',
    role: 'Senior Cloud Solution Architect',
    location: 'Lisbon, Portugal',
    timeZone: 'WEST (UTC+1)',
    languages: ['Portuguese', 'English', 'Spanish'],
    skills: ['Dataverse DLP', 'Security architecture', 'Power Platform'],
    certifications: ['Power Platform Functional Consultant'],
    availability: 'This week',
    mentor: false,
    optedIn: true,
  },
  {
    id: 'luciana-rocha',
    name: 'Luciana Rocha',
    initials: 'LR',
    role: 'Power Platform Engineering Lead',
    location: 'Redmond, United States',
    timeZone: 'PDT (UTC-7)',
    languages: ['Portuguese', 'English'],
    skills: ['Dataverse DLP', 'Tenant governance', 'Center of Excellence'],
    certifications: ['Power Platform Developer Associate'],
    availability: 'This week',
    mentor: true,
    optedIn: true,
    community: 'HOLA',
  },
  {
    id: 'samira-khan',
    name: 'Samira Khan',
    initials: 'SK',
    role: 'Principal AI Architect',
    location: 'London, United Kingdom',
    timeZone: 'BST (UTC+1)',
    languages: ['English', 'Urdu'],
    skills: ['Azure AI', 'Copilot architecture', 'Responsible AI'],
    certifications: ['Azure Solutions Architect Expert'],
    availability: 'Today',
    mentor: true,
    optedIn: true,
  },
  {
    id: 'rafael-private',
    name: 'Rafael Almeida',
    initials: 'RA',
    role: 'Dataverse Security Specialist',
    location: 'Rio de Janeiro, Brazil',
    timeZone: 'BRT (UTC-3)',
    languages: ['Portuguese', 'English'],
    skills: ['Dataverse DLP', 'Power Platform governance'],
    certifications: ['Power Platform Solution Architect Expert'],
    availability: 'Today',
    mentor: true,
    optedIn: false,
  },
]

export const accelerationGoal: AccelerationGoal = {
  employee: 'Maria Oliveira',
  employeeInitials: 'MO',
  location: 'Recife, Brazil',
  title: 'Become a Principal Cloud Solution Architect in AI',
  horizon: '3-year goal',
  skillSignals: [
    { skill: 'AI solution architecture', level: 46, note: 'Core gap for the target role' },
    { skill: 'Executive influence', level: 52, note: 'Grown through sponsorship and visibility' },
    { skill: 'Customer-facing delivery', level: 71, note: 'Strong foundation to build on' },
  ],
}

export const accelerationOpportunities: Opportunity[] = [
  {
    id: 'mentor-ines',
    kind: 'Mentor',
    title: 'Mentor who made this exact move',
    owner: 'Ines Duarte',
    ownerInitials: 'ID',
    detail: 'Moved from CSA to Principal CSA (AI) and mentors through HOLA.',
    reason: 'Same transition, shares a language and community with you',
    timeframe: 'Opted in to mentor this quarter',
    action: 'Request mentorship',
    confirmation: 'Mentorship request drafted to Ines',
    optedIn: true,
  },
  {
    id: 'peer-bruno',
    kind: 'Peer',
    title: 'Recently promoted to Principal CSA',
    owner: 'Bruno Alves',
    ownerInitials: 'BA',
    detail: 'Promoted six weeks ago; offered to share what the path required.',
    reason: 'Just navigated the promotion you are targeting',
    timeframe: 'Available for a 30-min call',
    action: 'Request intro',
    confirmation: 'Intro drafted to Bruno',
    optedIn: true,
  },
  {
    id: 'sponsor-catherine',
    kind: 'Sponsor',
    title: 'Anchor leader open to new sponsees',
    owner: 'Catherine Mbeki',
    ownerInitials: 'CM',
    detail: 'Partner Director in Azure AI who sponsors emerging architects.',
    reason: 'Opted in to sponsor talent outside her direct org',
    timeframe: 'Reviews new sponsees monthly',
    action: 'Express interest',
    confirmation: 'Sponsorship interest logged for Catherine',
    optedIn: true,
  },
  {
    id: 'shadow-review',
    kind: 'Shadow',
    title: 'Shadow an AI architecture design review',
    owner: 'Azure AI Black Belts',
    ownerInitials: 'AB',
    detail: 'Observe a live customer AI architecture review next week.',
    reason: 'Direct exposure to the work of the target role',
    timeframe: 'Next Thursday, 2 seats left',
    action: 'Reserve seat',
    confirmation: 'Shadow seat reserved',
    optedIn: true,
  },
  {
    id: 'cohort-ai-lab',
    kind: 'Cohort',
    title: 'SCHIE Academy AI Architecture Lab',
    owner: 'SCHIE Academy',
    ownerInitials: 'SA',
    detail: 'Six-week applied cohort with a capstone reviewed by architects.',
    reason: 'Closes your top skill gap with hands-on practice',
    timeframe: 'Starts Oct 12',
    action: 'Enroll',
    confirmation: 'Enrolled in AI Architecture Lab',
    optedIn: true,
  },
  {
    id: 'community-hola',
    kind: 'Community',
    title: 'C+AI HOLA architects circle',
    owner: 'HOLA Community',
    ownerInitials: 'HC',
    detail: 'Portuguese-speaking architects sharing paths into AI leadership.',
    reason: 'Belonging and visibility with people on the same journey',
    timeframe: 'Meets biweekly',
    action: 'Join',
    confirmation: 'Joined the HOLA architects circle',
    optedIn: true,
  },
]
